import { Poppins } from 'next/font/google'
import "./globals.css";

const poppins = Poppins({ subsets:['latin'], weight:['100']})

export const metadata = {
  title: "My first next app",
  description: "Generated by Devindi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.variable }>
        <div className='wrapper'>
        <div className='row'>
          <h2>Global header</h2>
        </div>
        {children}
       <div className='row'>
        <h2>Global footer</h2>
       </div>
        </div>
      </body>
    </html>
  );
}
